### ISSUE TITLE
[ feature request ] Add Argon2id and XChaCha20-Poly1305

### ISSUE THREAD

**Issue by yonas** [levaidaniel/kc#6]
1. Use Argon2id for password hash.
2. Use XChaCha20-Poly1305 for encryption.

Preferably set these modern algorithms as the new default.

**Comment by levaidaniel** [comment]
Hi yonas,

Thanks for bringing this up!

There's now an initial implementation for an Argon2id KDF and a ChaCha20-Poly1305 cipher in `master`.
AFAICS OpenSSL currently doesn't support XChaCha20 so that's something in turn `kc` can't support, unfortunately.

Feel free to check it out - the parameters became a bit unorthodox by providing the memory cost and memory lanes as _generic_ positional arguments: `-1` and `-2`. The man page has been updated to reflect that.

**Comment by yonas** [comment]
@levaidaniel 

> AFAICS OpenSSL currently doesn't support XChaCha20 so that's something in turn kc can't support, unfortunately.

XChaCha20 is the only version of XChaCha20 that is safe, as far as I know.

Perhaps we could leverage [libsodium](https://doc.libsodium.org/advanced/stream_ciphers/xchacha20) to access XChaCha20 instead of relying on OpenSSL exclusively.

**Comment by levaidaniel** [comment]
> XChaCha20 is the only version of XChaCha20 that is safe, as far as I know.

Then I'm sure it'll be standardized and there will be a final RFC at some point, when OpenSSL will include it.

**Comment by yonas** [comment]
> Then I'm sure it'll be standardized and there will be a final RFC at some point, when OpenSSL will include it.

Introducing clients to less than the best security, though.
